name: filesaverplus
description: "FileSaverPlus is a Flutter plugin for saving files to device storage with cross-platform support for Android, iOS, Web, Windows, Linux, and macOS."
version: 0.0.5
repository: https://github.com/devamitkumartiwari/filesaverplus.git

environment:
  sdk: '>=3.7.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  path_provider: ^2.1.0
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.amit.filesaverplus
        pluginClass: FilesaverplusPlugin
      ios:
        pluginClass: FilesaverplusPlugin
      web:
        pluginClass: FileSaverPlusWeb
        fileName: filesaverplus_web.dart
      windows:
        dartPluginClass: FileSaverPlusWindows
        fileName: filesaverplus_windows.dart
      linux:
        dartPluginClass: FileSaverPlusLinux
        fileName: filesaverplus_linux.dart
      macos:
        pluginClass: FilesaverplusPlugin
        dartPluginClass: FileSaverPlusMacOS
        fileName: filesaverplus_macos.dart
