name: filesaverplus
description: "FileSaverPlus is a Flutter plugin that allows you to easily save files to the device’s local storage, providing cross-platform support for Android and iOS."
version: 0.0.2
repository: https://github.com/devamitkumartiwari/filesaverplus.git

homepage:

environment:
  sdk: '>=3.7.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.amit.filesaverplus
        pluginClass: FilesaverplusPlugin
      ios:
        pluginClass: FilesaverplusPlugin
